name: unpanic
description: "Log and track your triggers"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  share_plus: ^12.0.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/unpanic-icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/unpanic-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/unpanic-icon.png"
    background_color: "#000000"
    theme_color: "#6200EE"
  windows:
    generate: true
    image_path: "assets/unpanic-icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/unpanic-icon.png"
